### ISSUE TITLE
not support `backquote`

### ISSUE THREAD

**Issue by zwpaper** [gonzalezreal/swift-markdown-ui#106] opened 2022-06-03 11:01 UTC
not support `backquote`

seems it drop the 
```
` `
```
  , but not rendering anything different

**Comment by gonzalezreal** [comment] 2022-07-05 13:43
Could you please provide sample markdown and code to reproduce the issue?

**Comment by gonzalezreal** [comment] 2023-01-22 17:14
Closing due to staleness.

**Closed by gonzalezreal** 2023-01-22 17:14 UTC
